[project]
name = "laboratorio-datascience"
version = "0.1.0"
description = ""
authors = [
    {name = "fjrivera07",email = "fjriverabravo@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas (>=3.0.3,<4.0.0)",
    "polars (>=1.41.0,<2.0.0)",
    "numpy (>=2.4.6,<3.0.0)",
    "scikit-learn (>=1.8.0,<2.0.0)",
    "joblib (>=1.5.3,<2.0.0)",
    "pyarrow (>=24.0.0,<25.0.0)"
]

[tool.poetry]
packages = [{include = "laboratorio_datascience", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "mypy (>=2.1.0,<3.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "isort (>=8.0.1,<9.0.0)",
    "ruff (>=0.15.14,<0.16.0)",
    "pre-commit (>=4.6.0,<5.0.0)",
    "pytest (>=9.0.3,<10.0.0)",
    "jupyter (>=1.1.1,<2.0.0)",
    "notebook (>=7.5.6,<8.0.0)"
]
