FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml poetry.lock* ./

RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi --without dev --no-root

COPY . .

ENV PYTHONPATH=/app/src

EXPOSE 8000

CMD sh -c "alembic upgrade head && uvicorn orders_service.api.main:app --host 0.0.0.0 --port 8000"