"""Init

Revision ID: 6587db273dc4
Revises: 0357929277fd
Create Date: 2026-05-21 16:41:44.941177

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6587db273dc4"
down_revision: Union[str, Sequence[str], None] = "0357929277fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
